name: Go Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24'  # 使用您的 Go 版本

    - name: Install dependencies
      run: |
        go mod tidy  # 安裝和整理依賴

    - name: Build Go project
      run: |
        go build -o seminar-go .  # 編譯您的 seminar-go 專案

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # 從 GitHub Secrets 中獲取 SSH 密鑰
        chmod 600 ~/.ssh/id_rsa  # 設置正確的檔案權限
        echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null" >> ~/.ssh/config

    - name: Copy binary to EC2
      run: |
        scp -i ~/.ssh/id_rsa seminar-go ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/  # 將 Go 應用複製到 EC2

    - name: Restart Apache on EC2
      run: |
        # 使用 SSH 連接到 EC2 主機
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} <<- 'EOF'
          # 移動到 Go 應用的目錄
          cd /home/ubuntu
          # 啟動 Go 應用（背景運行）
          nohup ./seminar-go &  # 使用 nohup 保證 Go 應用在背景運行且不受 SSH 斷開影響
          # 確保 Go 應用成功啟動，且重啟 Apache
          sudo systemctl restart apache2
        EOF
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
